# Treating Missing Values

In [1]:
import os
os.getcwd()

'C:\\Users\\91918\\Desktop\\remote internship 2020\\python codes'

In [3]:
os.chdir("c:/Users/91918/Desktop/remote internship 2020/Data Sets")
os.getcwd()

'c:\\Users\\91918\\Desktop\\remote internship 2020\\Data Sets'

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
data1 = pd.read_csv('insurance1.csv')

In [8]:
data1

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [9]:
data1.isnull().any()

age         False
sex         False
bmi         False
children    False
smoker      False
region      False
charges     False
dtype: bool

In [10]:
# Since there is no particular column has missing values 
 # it is showing as false....

# Label Encoding

In [11]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
data1['region'] = labelencoder_y.fit_transform(data1['region'])

In [12]:
data1

age     sex     bmi  children smoker  region      charges
0      19  female  27.900         0    yes       3  16884.92400
1      18    male  33.770         1     no       2   1725.55230
2      28    male  33.000         3     no       2   4449.46200
3      33    male  22.705         0     no       1  21984.47061
4      32    male  28.880         0     no       1   3866.85520
...   ...     ...     ...       ...    ...     ...          ...
1333   50    male  30.970         3     no       1  10600.54830
1334   18  female  31.920         0     no       0   2205.98080
1335   18  female  36.850         0     no       2   1629.83350
1336   21  female  25.800         0     no       3   2007.94500
1337   61  female  29.070         0    yes       1  29141.36030

[1338 rows x 7 columns]

In [13]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
data1['smoker'] = labelencoder_y.fit_transform(data1['smoker'])

In [14]:
data1

age     sex     bmi  children  smoker  region      charges
0      19  female  27.900         0       1       3  16884.92400
1      18    male  33.770         1       0       2   1725.55230
2      28    male  33.000         3       0       2   4449.46200
3      33    male  22.705         0       0       1  21984.47061
4      32    male  28.880         0       0       1   3866.85520
...   ...     ...     ...       ...     ...     ...          ...
1333   50    male  30.970         3       0       1  10600.54830
1334   18  female  31.920         0       0       0   2205.98080
1335   18  female  36.850         0       0       2   1629.83350
1336   21  female  25.800         0       0       3   2007.94500
1337   61  female  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

In [15]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
data1['sex'] = labelencoder_y.fit_transform(data1['sex'])

In [16]:
data1.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [17]:
# splitting dataset in to Independent variable and dependent variable

In [18]:
x = data1.iloc[:, 0:6].values
y = data1.iloc[:, 6].values

In [19]:
x

array([[19.  ,  0.  , 27.9 ,  0.  ,  1.  ,  3.  ],
       [18.  ,  1.  , 33.77,  1.  ,  0.  ,  2.  ],
       [28.  ,  1.  , 33.  ,  3.  ,  0.  ,  2.  ],
       ...,
       [18.  ,  0.  , 36.85,  0.  ,  0.  ,  2.  ],
       [21.  ,  0.  , 25.8 ,  0.  ,  0.  ,  3.  ],
       [61.  ,  0.  , 29.07,  0.  ,  1.  ,  1.  ]])

In [20]:
y

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

# one Hot Encoding

In [21]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder(categorical_features=[1,4,5])
x=onehotencoder.fit_transform(x).toarray()

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [37]:
x

array([[ 1.  ,  0.  ,  0.  , ..., 19.  , 27.9 ,  0.  ],
       [ 0.  ,  1.  ,  1.  , ..., 18.  , 33.77,  1.  ],
       [ 0.  ,  1.  ,  1.  , ..., 28.  , 33.  ,  3.  ],
       ...,
       [ 1.  ,  0.  ,  1.  , ..., 18.  , 36.85,  0.  ],
       [ 1.  ,  0.  ,  1.  , ..., 21.  , 25.8 ,  0.  ],
       [ 1.  ,  0.  ,  0.  , ..., 61.  , 29.07,  0.  ]])

# Splitting The dataset in to Train set and Testing set

In [22]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 0)

# Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [24]:
X_train

array([[ 0.97676557, -0.97676557,  0.50466988, ..., -1.5330973 ,
        -0.40713453, -0.89833872],
       [ 0.97676557, -0.97676557,  0.50466988, ..., -0.03364163,
         0.32855417, -0.89833872],
       [ 0.97676557, -0.97676557,  0.50466988, ...,  0.89459283,
         2.56690911,  3.25603402],
       ...,
       [-1.02378711,  1.02378711,  0.50466988, ...,  0.03776102,
        -0.91016269, -0.89833872],
       [-1.02378711,  1.02378711,  0.50466988, ..., -1.46169465,
         0.76659782, -0.89833872],
       [ 0.97676557, -0.97676557,  0.50466988, ..., -0.46205754,
        -1.96596021, -0.06746417]])

In [25]:
X_test

array([[-1.02378711,  1.02378711,  0.50466988, ...,  0.89459283,
        -0.08863026, -0.06746417],
       [ 0.97676557, -0.97676557,  0.50466988, ...,  0.53757957,
        -0.22180837, -0.06746417],
       [-1.02378711,  1.02378711, -1.98149332, ...,  0.60898222,
         1.57449152,  0.76341038],
       ...,
       [-1.02378711,  1.02378711,  0.50466988, ...,  1.10880078,
         1.20785059, -0.89833872],
       [-1.02378711,  1.02378711,  0.50466988, ...,  1.75142463,
         1.34905148, -0.06746417],
       [ 0.97676557, -0.97676557,  0.50466988, ...,  1.60861933,
        -0.92299913, -0.89833872]])